_BASE_: "../Base_det.yaml"


DATASETS:
  TRAIN: ("film_test",)
  TEST: ("film_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (375000,)
  MAX_ITER: 435000
  CHECKPOINT_PERIOD: 100000

TEST:
  EVAL_PERIOD: 10000